### PR TITLE
Update data set to 2018-03-05

### PR DESCRIPTION
**Pull request by irrenhaus**

### CODE REVIEW

**Comment by olivere** [comment]
@dmke Hi Dominik, can you please review this change? I don't feel competent enough any more with regards to BLZ to see if this is or isn't a valid PR.

**Comment by dmke** [comment]
Sure, give me a moment :-)

**Comment by dmke** [comment]
@irrenhaus Your `.tsv.gz` contains tab characters in some bank names, which leads to unnecessary quotation marks.

How did you convert this file? I usually open the `.xlsx` file in LibreOffice Calc, hit Ctrl+Shift+S, select CSV from the format dropdown, save it somewhere before I use my text editor to remove the first line, save it as `data/whatever.tsv` and running it through gzip.

I'm curious about your process.

**Comment by dmke** [comment]
I've updated your data file with a sanitized version, I hope you don't mind.

**Comment by dmke** [comment]
For reference: 332c47d01c218ca7fb60742654ca0427f35b6133.

**Comment by olivere** [comment]
Thank you! 👍

**Comment by irrenhaus** [comment]
Hey thanks a lot! I exported this with some Mac application, being new to Mac, I guess I did something in a way apple doesn't want it to be done.

**Comment by dmke** [comment]
Well, don't worry. Preparing the data files involves working around some pitfalls (one of them converting from ISO-8895-15 to UTF-8 encoding).

I've added some scripts for #14 and #15, so in future updating the files is less... painful. But now that we have these scripts, what are the chances the Bundesbank stops publishing the source files? :grin:

**Pull request closed without merging**
